/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pbl.view;

import javax.swing.JOptionPane;
import pbl.controller.ControllerConexao;
import pbl.controller.ControllerJogo;

/**
 *
 * @author emerson
 */
public class BolaoDeEsportes extends javax.swing.JDialog {

    ControllerJogo controllerJogo;
    ControllerConexao controllerConexao;
    
    /**
     * Creates new form BolaoDeEsportes
     */
    public BolaoDeEsportes(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        controllerJogo = ControllerJogo.getInstance();
        controllerConexao = controllerJogo.getControllerConexao();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        numeros = new javax.swing.JComboBox<>();
        Escolher = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 3, 15)); // NOI18N
        jLabel1.setText("BOLÃO DE ESPORTES, ESCOLHA UM NÚMERO:");

        numeros.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6" }));

        Escolher.setText("Escolher");
        Escolher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EscolherActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(numeros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(Escolher)))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(numeros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(Escolher)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EscolherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EscolherActionPerformed
        int numero = (numeros.getSelectedIndex()+1);
        
        if(controllerJogo.buscarBilheteBolao(numero)!=null){
            JOptionPane.showConfirmDialog(null, "Numero Já escolhido");
        }else{
            controllerConexao.participarBolaoEsportes(numero);
            this.dispose();
        }

    }//GEN-LAST:event_EscolherActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton Escolher;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JComboBox<String> numeros;
    // End of variables declaration//GEN-END:variables
}
