/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pbl.view;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JLabel;
import pbl.controller.ControllerJogo;
import pbl.model.jogo.Peao;

/**
 *
 * @author marcos
 */
public class Tabuleiro extends javax.swing.JPanel {

    /**
     * Creates new form Tabuleiro
     */
    private final ControllerJogo controllerJogo;
    private List<Peao> peoes;
    private Tabuleiro tabuleiro;
    private JLabel imagemFundo;
    private Peao peaoPrincipal;

    public Tabuleiro() {
        initComponents();
        this.peoes = new ArrayList<>();
        this.controllerJogo = ControllerJogo.getInstance();
        gerarGUI();
//        adicionarPeoesTabuleiro();
    }


    public void adicionarPeoesTabuleiro() {
        this.removeAll();
        this.peaoPrincipal = controllerJogo.getJogador().getPeao();
        this.add(peaoPrincipal);
        this.peoes = controllerJogo.getPeoes();
        for (Peao peao : peoes) {
            this.add(peao);
        }
        validate();
        repaint();
    }

    @Override
    public void paintComponent(Graphics g){
        //Desenhando tabuleiro;
        Graphics2D g2d = (Graphics2D) g;
        super.paintComponent(g);
        g2d.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON); //Deixa mais bonitinho
        g.setColor(Color.black);
        //Retangulo laterais
        g.drawRect(0, 0, 719, 480);
        //Linha verticais
        g.drawLine(102, 0, 102, 480);
        g.drawLine(204, 0, 204, 480);
        g.drawLine(306, 0, 306, 480);
        g.drawLine(408, 0, 408, 480);
        g.drawLine(510, 0, 510, 480);
        g.drawLine(612, 0, 612, 480);
        //Linha horizontais
        g.drawLine(0, 96,  720, 96);
        g.drawLine(0, 192, 720, 192);
        g.drawLine(0, 288, 720, 288);
        g.drawLine(0, 384, 720, 384);
        
    }
    private void gerarGUI() {
        this.setLayout(null);
        this.setBackground(Color.white);
        this.setSize(480, 720);
    }

    public void atualizarTabuleiro() {
        this.peaoPrincipal = controllerJogo.getJogador().getPeao();
        this.peoes = controllerJogo.getPeoes();
        repaint();
//        imagemFundo.repaint();
    }

    private void removerPeao(Peao p) {
        this.remove(p);
        this.validate();
    }

    private void limparTabuleiro() {

        this.removeAll();
        this.validate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
