/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pbl.view;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.GridLayout;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import pbl.model.jogo.Peao;

/**
 *
 * @author marcos
 */
public class Tabuleiro extends javax.swing.JPanel {

    /**
     * Creates new form Tabuleiro
     */
    private final List<Peao> peoes;
    private Tabuleiro tabuleiro;

    public Tabuleiro() {
        initComponents();
        this.peoes = new ArrayList<>();
        gerarGUI();
    }

    //Metodo para testar movimento de objeto;
    public void andar(int casas) throws InterruptedException {
        Peao p = peoes.get(0);
        p.andarCasas(1);
        atualizarLocalInterface();
    }

    public void adicionarPeao(Peao peao) {
        peoes.add(peao);
        this.add(peao);
        atualizarLocalInterface();
    }

    private void gerarGUI() {
        this.setLayout(new BorderLayout());
        this.setBackground(Color.white);
        this.setSize(480, 720);
        //    this.add(new JButton());

    }

    public void atualizarLocalInterface() {
//        limparTabuleiro();
        for (Peao peao : peoes) {
//            removerPeao(peao);
            System.out.println("Peao \nX: " + peao.getX() + "\nY: " + peao.getY());
//            this.add(new JButton());
        }
//        repaint();
//        validate();
    }

    private void removerPeao(Peao p) {
        this.remove(p);
        this.validate();
    }

    private void limparTabuleiro() {

        this.removeAll();
        this.validate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
